display_name: Hiddify
publisher_display_name: Hiddify
identity_name: Hiddify.HiddifyNext
msix_version: 4.0.5.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: ar, en-us, es-es, fa-ir, fr-fr, id-id, pt-br, ru-ru, tr-tr, zh-cn, zh-tw
protocol_activation: hiddify, v2ray, v2rayn, v2rayng, clash, clashmeta, sing-box
execution_alias: hiddify
certificate_path: windows\sign.pfx
certificate_password:
publisher: CN=8CB43675-F44B-4AA5-9372-E8727781BDC4
install_certificate: "false"
enable_at_startup: "true"
startup_task:
  parameters: --autostart

# For testing with a self-signed certificate
# publisher: CN=Hiddify-Test
# certificate_password: "1234"
# install_certificate: "true"