app_id: 6L903538-42B1-4596-G479-BJ779F21A65D
publisher: Hiddify
publisher_url: https://github.com/hiddify/hiddify-app
display_name: Hiddify
create_desktop_icon: true
install_dir_name: "{autopf64}\\Hiddify"
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - es
  - fr
  - pt
  - ru
  - tr
script_template: inno_setup.sas
